//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public long VoteID { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string PollingDistrict { get; set; }
        public string PollingDivision { get; set; }
        public Nullable<int> Party_ID { get; set; }
        public Nullable<int> Candidate_ID { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Party Party { get; set; }
    }
}
